import { useState, useRef, useEffect } from 'react'

// ─── Pre-built FAQ Knowledge Base ─────────────────────
const FAQ = [
  {
    keywords: ['what is skope', 'how does skope work', 'what does skope do', 'what is this'],
    answer: "Skope is an AI-powered career discovery platform for Indian Class 12 students. You answer a set of blunt, honest questions about your marks, interests, and goals. Skope then generates a personalized PathReport — a brutally honest breakdown of the best careers, colleges, and courses for you specifically, including hidden gems most students never hear about."
  },
  {
    keywords: ['pathreport', 'path report', 'what is a pathreport', 'what is pathreport'],
    answer: "A PathReport is your personalized career analysis generated by Skope. It includes: your strength and gap analysis, 3 career paths matched to your profile, 8 college recommendations (including hidden gems), recommended courses, hidden career fields nobody talks about, and a 5-step action plan. Think of it as a mirror — not a pep talk."
  },
  {
    keywords: ['is my data private', 'data privacy', 'data safe', 'information safe', 'secure', 'privacy'],
    answer: "Your data stays with us and is not shared with third parties. Your PathReport is stored securely and linked to your account only. We use Firebase Authentication for secure login. The information you provide is only used to generate your personalized PathReport."
  },
  {
    keywords: ['how long', 'time does it take', 'how much time', 'duration'],
    answer: "The entire process takes about 10-15 minutes. Phase 1 has 5 direct questions (2-3 min). Phase 2 is a 8-question adaptive interview (5-7 min). Then preferences (1 min). Your PathReport is generated in about 30-60 seconds after that."
  },
  {
    keywords: ['cost', 'free', 'paid', 'price', 'subscription', 'money'],
    answer: "Skope is currently free to use. You just need to create an account with Google or email/OTP and you can generate your PathReport at no cost."
  },
  {
    keywords: ['hidden gem', 'hidden gems', 'lesser known', 'unknown colleges'],
    answer: "Hidden gem colleges are genuinely excellent institutions that most students and parents have never heard of — but often outperform well-known brands in placements, teaching quality, or specific career outcomes. Examples: Plaksha University, DAIICT, IISER campuses, Krea University, UPES Dehradun, Shiv Nadar University. Skope always includes at least 3 hidden gems in your report."
  },
  {
    keywords: ['hidden courses', 'unknown courses', 'career nobody knows', 'unusual career'],
    answer: "Hidden courses are real, in-demand fields that almost no student knows exist. Examples: Actuarial Science (8-15 LPA starting, less than 500 qualified under-30 in India), Geomatics Engineering (ISRO, defence), Clinical Data Management (pharma), UX Research, Marine Engineering, Computational Linguistics. Skope includes 3 of these in your PathReport based on your profile."
  },
  {
    keywords: ['reddit', 'reddit verdict', 'what students say', 'student reviews'],
    answer: "Skope's college recommendations include a 'Reddit Verdict' — a 1-2 sentence summary of what actual students say on Reddit, Quora, and college forums about each college. This is the insider opinion, not the marketing brochure version."
  },
  {
    keywords: ['entrance exam', 'exams', 'uceed', 'cuet', 'jee', 'neet', 'lsat', 'iiser', 'nest'],
    answer: "Skope always recommends entrance exams you might not know about alongside the usual ones. For example: UCEED (IIT design), IISER IAT (top science schools), LSAT India (law at 80+ colleges), IPMAT (IIM integrated MBA), TISS NET (social work/HR), NCHM JEE (hotel management), JGEEBILS (top research institutes). Most students only know JEE and NEET — there is a whole world beyond those."
  },
  {
    keywords: ['can i redo', 'redo', 'retake', 'another report', 'new report', 'do again'],
    answer: "Yes! You can click 'Retake Test' in the app to start fresh and generate a new PathReport anytime. Each new report takes your current answers, so if your marks or exam situation changes, do it again."
  },
  {
    keywords: ['download', 'pdf', 'save', 'share', 'export'],
    answer: "Yes — from the ResultPage (PathReport page), you can click the 'Download PDF' button to save your entire PathReport as a printable PDF. You can also use the 'Share' button to share the report link or share Skope with friends via WhatsApp, Twitter, or copy link."
  },
  {
    keywords: ['profile', 'edit profile', 'change name', 'account'],
    answer: "You can access your profile from the Navbar (click your avatar/initials in the top right). The profile page shows your account info, and you can edit your display name there."
  },
  {
    keywords: ['login', 'sign in', 'sign up', 'create account', 'register', 'google', 'otp', 'phone'],
    answer: "You can sign in using: (1) Google Sign-in — fastest, one click. (2) Email and Password — standard signup. (3) Phone OTP — enter your Indian mobile number and get a 6-digit SMS code. All methods are secure and free."
  },
  {
    keywords: ['marks too low', 'low marks', 'bad marks', 'fail', 'not good', 'weak'],
    answer: "Skope works for every mark range. The PathReport is more honest the lower your marks are — it will not pretend IIT is realistic with 60% boards. It will show you what IS actually achievable, what hidden gem colleges fit your real profile, and what career paths make sense. Low marks do not mean bad career. They just mean different options than what your friends are chasing."
  },
  {
    keywords: ['after 12th', 'what to do', 'confused', 'do not know', 'no idea'],
    answer: "That is exactly why Skope exists. Start the test — answer the questions honestly, including if you are confused. The interview phase is specifically designed to dig out what you actually want vs what you think you want. The PathReport is most useful when you are genuinely uncertain."
  }
]

function findAnswer(input) {
  const q = input.toLowerCase()
  for (const item of FAQ) {
    if (item.keywords.some(kw => q.includes(kw))) {
      return item.answer
    }
  }
  return "I don't have a specific answer for that, but here's what I can help with: how Skope works, what a PathReport is, hidden gem colleges, unknown career fields, exam suggestions, data privacy, login help, and download/share features. Try asking about any of those!"
}

// ─── HelpBot Component ─────────────────────────────────
export default function HelpBot() {
  const [open, setOpen] = useState(false)
  const [messages, setMessages] = useState([
    { role: 'bot', text: "Hey! I'm Skope's help assistant. Ask me anything — how the app works, what exams you should know about, or what a PathReport actually contains." }
  ])
  const [input, setInput] = useState('')
  const [pulse, setPulse] = useState(true)
  const messagesEndRef = useRef(null)

  useEffect(() => {
    if (open) {
      messagesEndRef.current?.scrollIntoView({ behavior: 'smooth' })
      setPulse(false)
    }
  }, [messages, open])

  const handleSend = () => {
    const q = input.trim()
    if (!q) return
    const answer = findAnswer(q)
    setMessages(prev => [
      ...prev,
      { role: 'user', text: q },
      { role: 'bot', text: answer }
    ])
    setInput('')
  }

  const handleKey = (e) => {
    if (e.key === 'Enter') handleSend()
  }

  const quickQuestions = [
    "What is a PathReport?",
    "What are hidden gem colleges?",
    "Is my data private?",
    "Can I download my report?"
  ]

  return (
    <>
      {/* Floating Button */}
      <button
        id="helpbot-toggle"
        onClick={() => setOpen(!open)}
        className="fixed bottom-6 right-6 z-50 w-14 h-14 rounded-full border-none cursor-pointer flex items-center justify-center shadow-[0_8px_30px_rgba(79,142,247,0.35)] transition-all duration-300 hover:scale-110"
        style={{ background: 'linear-gradient(135deg, #4f8ef7, #8b5cf6)' }}
        aria-label="Help"
      >
        {open ? (
          <svg width="20" height="20" viewBox="0 0 24 24" fill="none">
            <path d="M18 6L6 18M6 6L18 18" stroke="white" strokeWidth="2.5" strokeLinecap="round" />
          </svg>
        ) : (
          <svg width="22" height="22" viewBox="0 0 24 24" fill="none">
            <path d="M12 22C17.5228 22 22 17.5228 22 12C22 6.47715 17.5228 2 12 2C6.47715 2 2 6.47715 2 12C2 17.5228 6.47715 22 12 22Z" stroke="white" strokeWidth="2"/>
            <path d="M9 9C9 7.34315 10.3431 6 12 6C13.6569 6 15 7.34315 15 9C15 10.6569 13.6569 12 12 12V13" stroke="white" strokeWidth="2" strokeLinecap="round"/>
            <circle cx="12" cy="16.5" r="0.75" fill="white" stroke="white" strokeWidth="0.5"/>
          </svg>
        )}
        {pulse && !open && (
          <span className="absolute top-0 right-0 w-3.5 h-3.5 rounded-full bg-[#6bcb77] border-2 border-[#080b14] animate-pulse" />
        )}
      </button>

      {/* Chat Panel */}
      {open && (
        <div
          className="fixed bottom-24 right-6 z-50 w-[340px] max-w-[calc(100vw-24px)] rounded-[20px] overflow-hidden animate-fadeUp"
          style={{
            background: 'rgba(10, 14, 26, 0.92)',
            backdropFilter: 'blur(20px)',
            border: '1px solid rgba(79,142,247,0.15)',
            boxShadow: '0 20px 60px rgba(0,0,0,0.5), 0 0 0 1px rgba(255,255,255,0.04)'
          }}
        >
          {/* Header */}
          <div className="flex items-center gap-3 px-4 py-3.5 border-b border-[rgba(79,142,247,0.1)]"
            style={{ background: 'linear-gradient(135deg, rgba(79,142,247,0.08), rgba(139,92,246,0.08))' }}>
            <div className="w-9 h-9 rounded-full flex items-center justify-center shrink-0"
              style={{ background: 'linear-gradient(135deg, #4f8ef7, #8b5cf6)' }}>
              <svg width="16" height="16" viewBox="0 0 24 24" fill="none">
                <path d="M12 22C17.5228 22 22 17.5228 22 12C22 6.47715 17.5228 2 12 2C6.47715 2 2 6.47715 2 12C2 17.5228 6.47715 22 12 22Z" stroke="white" strokeWidth="2"/>
                <path d="M9 9C9 7.34315 10.3431 6 12 6C13.6569 6 15 7.34315 15 9C15 10.6569 13.6569 12 12 12V13" stroke="white" strokeWidth="2" strokeLinecap="round"/>
                <circle cx="12" cy="16.5" r="0.75" fill="white" stroke="white" strokeWidth="0.5"/>
              </svg>
            </div>
            <div>
              <div className="font-sora text-[13px] font-semibold text-white">Skope Help</div>
              <div className="font-dm text-[10px] text-[#6bcb77] flex items-center gap-1">
                <span className="w-1.5 h-1.5 rounded-full bg-[#6bcb77] inline-block animate-pulse" />
                Always available
              </div>
            </div>
          </div>

          {/* Messages */}
          <div className="max-h-[280px] overflow-y-auto px-4 py-3 flex flex-col gap-3">
            {messages.map((msg, i) => (
              <div key={i} className={`flex ${msg.role === 'user' ? 'justify-end' : 'justify-start'}`}>
                <div
                  className={`max-w-[85%] px-3.5 py-2.5 rounded-[14px] font-dm text-[12.5px] leading-[1.65] ${
                    msg.role === 'user'
                      ? 'bg-gradient-to-r from-[rgba(79,142,247,0.2)] to-[rgba(139,92,246,0.2)] text-white border border-[rgba(139,92,246,0.2)] rounded-tr-[4px]'
                      : 'bg-[rgba(255,255,255,0.04)] text-[rgba(240,242,255,0.8)] border border-[rgba(255,255,255,0.06)] rounded-tl-[4px]'
                  }`}
                >
                  {msg.text}
                </div>
              </div>
            ))}
            <div ref={messagesEndRef} />
          </div>

          {/* Quick questions — only shown at start */}
          {messages.length <= 1 && (
            <div className="px-4 pb-2 flex flex-wrap gap-1.5">
              {quickQuestions.map((q, i) => (
                <button
                  key={i}
                  onClick={() => {
                    const answer = findAnswer(q)
                    setMessages(prev => [...prev, { role: 'user', text: q }, { role: 'bot', text: answer }])
                  }}
                  className="font-dm text-[11px] text-[rgba(240,242,255,0.55)] bg-[rgba(255,255,255,0.04)] border border-[rgba(79,142,247,0.12)] rounded-full px-2.5 py-1 cursor-pointer hover:border-blue hover:text-blue transition-all duration-200"
                >
                  {q}
                </button>
              ))}
            </div>
          )}

          {/* Input */}
          <div className="flex items-center gap-2 px-4 py-3 border-t border-[rgba(79,142,247,0.08)]">
            <input
              type="text"
              className="flex-1 bg-[rgba(255,255,255,0.04)] border border-[rgba(255,255,255,0.08)] rounded-[10px] px-3 py-2 text-white font-dm text-[12.5px] outline-none focus:border-[rgba(79,142,247,0.3)] transition-colors placeholder:text-[rgba(240,242,255,0.2)]"
              placeholder="Ask anything..."
              value={input}
              onChange={e => setInput(e.target.value)}
              onKeyDown={handleKey}
            />
            <button
              onClick={handleSend}
              disabled={!input.trim()}
              className="w-8 h-8 rounded-[8px] flex items-center justify-center border-none cursor-pointer transition-all duration-200 disabled:opacity-30 disabled:cursor-not-allowed shrink-0"
              style={{ background: 'linear-gradient(135deg, #4f8ef7, #8b5cf6)' }}
            >
              <svg width="14" height="14" viewBox="0 0 24 24" fill="none">
                <path d="M5 12H19M19 12L13 6M19 12L13 18" stroke="white" strokeWidth="2.5" strokeLinecap="round" strokeLinejoin="round" />
              </svg>
            </button>
          </div>
        </div>
      )}
    </>
  )
}
